name: flutter_ev_concept_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  flutter_riverpod: ^2.5.1
  get: ^4.6.6
  go_router: ^14.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
